site_name: call-limiter
site_description: Rate Limiter with retry for execution pacing and resilience.
site_url: https://call-limiter.readthedocs.io
repo_url: https://github.com/eyukselen/call-limiter
repo_name: eyukselen/call-limiter

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.code.copy

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [.]
          options:
            show_source: true
            show_root_heading: true
            heading_level: 3
            docstring_style: google
  - mermaid2

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
  - pymdownx.snippets:
      base_path: [ "." ]
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - tables

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - API Reference: api.md
  - Examples: examples.md
  - Burst Modes: burst_mode.md
